name: Build and Tag

on:
  schedule:
    - cron: '0 3 * * 1'  # Weekly Monday 03:00 UTC
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main
      - stable
  workflow_dispatch:

jobs:
  build-scan-push:
    uses: r0ps3c/gh-shared-workflows/.github/workflows/docker-build-scan-push.yml@dc21cd79ac836d142191378dd8fe81d63a481933 # main
    with:
      image-ref: postfix-ses:main
      primary_branch: main
      version-extract-command: "apk info postfix 2>/dev/null | grep '^postfix-' | head -1 | cut -d- -f2 | cut -dr -f1"
      test-command: make test
    secrets: inherit
