name: "build"

on:
  push:
    tags:
      - "!v*"
    branches:
      - "*"

  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ github.repository }}:${{github.sha}}-test
          cache-to: type=gha

      - name: Test
        run: |
          docker run -e POSTFIX_CHECK=1 --rm ${{ github.repository }}:${{github.sha}}-test -r 127.0.0.1 -n 127.0.0.1/8 -d test.local -s 127.0.0.1 -u test -p test -m test@local
